doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        charset: utf8
        default_table_options:
            collate: utf8_unicode_ci

        # backtrace queries in profiler (increases memory usage per request)
        #profiling_collect_backtrace: '%kernel.debug%'
    orm:
        auto_generate_proxy_classes: "%kernel.debug%" # default: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        filters:
            matching_context_public_filter: App\Doctrine\MatchingContextPublicFilter
        dql:
            datetime_functions:
                date_format: DoctrineExtensions\Query\Mysql\DateFormat
        mappings:
            App:
                type: annotation
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App