sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        environment: staging
        excluded_exceptions: #exclude validation errors
            - App\Exception\UserNotFoundException
            - Symfony\Component\Security\Core\Exception\AccessDeniedException
#        register_error_listener: false # Disables the ErrorListener
#        monolog:
#            error_handler:
#                enabled: true
#                level: error
