version: '3.4'
services:
  php:
    container_name: kraft-backend_php
    build:
      context: .
      target: platform_php
    depends_on:
    - db
    - dbtest

  db:
    container_name: kraft-backend_db
    image: mariadb:10.2
    ports:
    - '3308:3306'
    volumes:
    - /var/lib/postgresql/data
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=lmem
    - MYSQL_PASSWORD=meml
    - MYSQL_DATABASE=kraftbackenddev
    restart: unless-stopped

  dbtest:
    container_name: kraft-backend_dbtest
    image: mariadb:10.2
    ports:
    - '3309:3306'
    volumes:
      - /var/lib/postgresql/data
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=lmem
    - MYSQL_PASSWORD=meml
    - MYSQL_DATABASE=kraftbackenddev
    restart: unless-stopped
