nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: true
        forced_allow_origin_value: '*'
    paths:
        '^/api/v3/':
            allow_origin: ['^https?://localhost:[0-9]+', 'https?:\/\/(\S+\.)*dismoi\.io']
            allow_methods: ['POST', 'GET']
            max_age: 3600
