easy_admin:
    site_name: 'DisMoi'
    design:
        assets:
            css:
                - 'css/admin.css'
            js:
                - 'js/regex_validator.js'
                - 'js/chartjs/moment.min.js'
                - 'js/chartjs/Chart.js'
                - 'js/custom_graph.js'
                - 'js/short-and-sweet/short-and-sweet.js'
                - 'js/message_validator.js'
                - 'js/filter_table_row.js'
                - 'js/select2.js'
    entities:
        Notice:
            class: AppBundle\Entity\Notice
            label: menu.notices
            actions: ['show']
            search:
                fields:
                    - id
                    - matchingContexts.description
                    - matchingContexts.exampleUrl
                    - matchingContexts.urlRegex
                    - matchingContexts.excludeUrlRegex
                    - excludeUrlRegex
                    - contributor.name
                    - message
                    - note
                    - expires
            show:
                fields:
                    - { property: message, label: notices.message }
                    - { property: contributor, label: notices.contributor }
                    - { property: relayers, label: notices.relayers }
                    - { property: screenshot, template: 'vich_uploader_screenshot.html.twig', label: notices.screenshot }
                    - { property: note, label: notices.note }
                    - { property: visibility, label: notices.visibility }
                    - { property: excludeUrlRegex, label: notices.excludeUrlRegex }
                    - { property: matchingContexts, label: notices.matchingContexts }
                    - { property: expires, label: notices.expires }
                    - { property: unpublishedOnExpiration, label: notices.unpublishedOnExpiration }
            form:
                fields:
                    - { type: group, label: notices.groups.publication, icon: comments }
                    - { property: message, label: notices.message }
                    - { property: contributor, label: notices.contributor, type_options: { 'query_builder': 'AppBundle\Repository\ContributorRepository::getOrderedList' }}
                    - property: relayers,
                      label: notices.relayers,
                      type: easyadmin_autocomplete,
                      type_options: {
                          class: 'AppBundle\Entity\Contributor',
                          multiple: true
                      }
                    - { property: screenshotFile, label: notices.screenshot, type: vich_image, help: notices.screenshot.help }
                    - { property: note, label: notices.note }
                    - { property: visibility, label: notices.visibility, type: 'AppBundle\Form\VisibilityType' }
                    - { type: group, label: notices.groups.matchingContexts, icon: 'paper-plane', columns: 6 }
                    - property: matchingContexts,
                      type: collection,
                      label: notices.matchingContexts,
                      type_options: {
                          required: true,
                          entry_type: 'AppBundle\Form\MatchingContextType',
                          allow_add: true,
                          allow_delete: true,
                          by_reference: false
                      }
                    - { property: excludeUrlRegex, label: notices.excludeUrlRegex, type: textarea }
                    - { type: group, label: Lifecycle, icon: recycle, columns: 6 }
                    - { property: expires, label: notices.expires }
                    - { property: unpublishedOnExpiration, label: notices.unpublishedOnExpiration }

            list:
                title: title.notices
                actions: ['show']
                fields:
                    - { property: id, label: notices.id }
                    - { property: contributor, label: notices.contributor }
                    - property: relayersCount,
                      label: notices.relayers
                    - { property: message, label: notices.message }
                    - { property: visibility, label: notices.visibility }
                    - { property: matchingContexts, label: notices.matchingContexts }
                    - { property : badgedRatingCount, label: notices.badgedRatingCount, css_class: 'graphable' }
                    - { property : displayedRatingCount, label: notices.displayedRatingCount, css_class: 'graphable' }
                    - { property : unfoldedRatingCount, label: notices.unfoldedRatingCount, css_class: 'graphable' }
                    - { property : clickedRatingCount, label: notices.clickedRatingCount, css_class: 'graphable' }
                    - { property : likedRatingCount, label: notices.likedRatingCount, css_class: 'graphable' }
                    - { property : dislikedRatingCount, label: notices.dislikedRatingCount, css_class: 'graphable' }
                    - { property : dismissedRatingCount, label: notices.dismissedRatingCount, css_class: 'graphable' }
                    - { property: expires, label: notices.expires }
                    - { property: created, label: notices.created }
                    - { property: updated, label: notices.updated }

        ExpiredNotice:
            class: AppBundle\Entity\Notice
            label: menu.expiredNotices
            disabled_actions: ['new']
            search:
                fields:
                    - matchingContexts.exampleUrl
                    - matchingContexts.urlRegex
                    - matchingContexts.excludeUrlRegex
                    - excludeUrlRegex
                    - contributor.name
                    - message
                    - note
                    - expires
            list:
                title: title.expiredNotices
                dql_filter: 'entity.expires <= CURRENT_TIMESTAMP()'
                fields:
                    - { property: id, label: notices.id }
                    - { property: contributor, label: notices.contributor }
                    - { property: message, label: notices.message }
                    - { property: visibility, label: notices.visibility }
                    - { property: matchingContexts, label: notices.matchingContexts }
                    - { property: badgedRatingCount, label: notices.badgedRatingCount, css_class: 'graphable' }
                    - { property: displayedRatingCount, label: notices.displayedRatingCount, css_class: 'graphable' }
                    - { property: unfoldedRatingCount, label: notices.unfoldedRatingCount, css_class: 'graphable' }
                    - { property: clickedRatingCount, label: notices.clickedRatingCount, css_class: 'graphable' }
                    - { property: likedRatingCount, label: notices.likedRatingCount, css_class: 'graphable' }
                    - { property: dislikedRatingCount, label: notices.dislikedRatingCount, css_class: 'graphable' }
                    - { property: dismissedRatingCount, label: notices.dismissedRatingCount, css_class: 'graphable' }
                    - { property: expires, label: notices.expires }
                    - { property: unpublishedOnExpiration, label: notices.unpublishedOnExpiration }
            form:
                fields:
                    - { type: group, label: notices.groups.publication, icon: comments }
                    - { property: message, label: notices.message }
                    - { property: contributor, label: notices.contributor, type_options: { 'query_builder': 'AppBundle\Repository\ContributorRepository::getOrderedList' }}
                    - { property: note, label: notices.note }
                    - { property: visibility, label: notices.visibility, type: 'AppBundle\Form\VisibilityType' }
                    - { type: group, label: notices.groups.matchingContexts, icon: 'paper-plane', columns: 6 }
                    - property: matchingContexts,
                      type: collection,
                      label: notices.matchingContexts,
                      type_options: {
                          required: true,
                          entry_type: 'AppBundle\Form\MatchingContextType',
                          allow_add: true,
                          allow_delete: true,
                          by_reference: false
                      }
                    - { property: excludeUrlRegex, label: notices.excludeUrlRegex, type: textarea }
                    - { type: group, label: Lifecycle, icon: recycle, columns: 6 }
                    - { property: expires, label: notices.expires }
                    - { property: unpublishedOnExpiration, label: notices.unpublishedOnExpiration }

        Contributor:
            label: menu.contributors
            class: AppBundle\Entity\Contributor
            controller: AppBundle\Controller\ContributorAdminController
            list:
                title: title.contributors
                sort: [name, ASC]
                fields:
                    - { property: id, label: contributors.id }
                    - { property: image, template: 'vich_uploader_image.html.twig', label: contributors.image }
                    - { property: name, label: contributors.name }
                    - { property: email, label: contributors.email }
                    - { property: intro, label: contributors.intro }
                    - { property: activeSubscriptionsCount, label: contributors.activeSubscriptionsCount }
                    - { property: enabled, label: contributors.enabled }
                    - { property: starredNotice, type: object, template: 'notice_in_list.html.twig', label: contributors.starredNotice }
            form:
                fields:
                    - { property: name, label: contributors.name, type_options: { required: true } }
                    - {
                        property: categories,
                        label: contributors.categories,
                        type: 'AppBundle\Form\CategoryNameType'
                      }
                    - { property: email, label: contributors.email }
                    - { property: website, label: contributors.website }
                    - { property: intro, label: contributors.intro }
                    - { property: imageFile, label: contributors.imageFile, type: vich_image, help: contributors.imageFile.help }
                    - { property: bannerImageFile, label: contributors.bannerImageFile, type: vich_image, help: contributors.bannerImageFile.help }
                    - { property: starredNotice, label: contributors.starredNotice }
                    - { type: group, label: contributors.groups.social_media, icon: 'paper-plane', columns: 1 }
                    - { property: title, label: contributors.title, help: "Ce titre remplace le nom du contributor lors d'un partage." }
                    - { property: previewImageFile, label: contributors.previewImageFile, type: vich_image, help: '1200x630 pixels, JPG, PNG.' }

        Domain:
            label: menu.domains
            class: AppBundle\Entity\DomainName
            list:
                title: title.domains
                actions: ['show']
                sort: ['name', 'ASC']
                fields:
                    - { property: prettyName, label: domains.name }
                    - { property: sets, label: domains.sets.nb }
                    - { property: matchingContexts, label: domains.matchingContexts.nb }
            form:
                fields:
                    - { property: name, label: domains.name }
                    - { property: path, label: domains.path }
            show:
                max_results: 100
                fields:
                    - { property: id, label: domains.id }
                    - { property: prettyName, label: domains.name }
                    - { property: sets, label: domains.sets }
                    # ugly but https://github.com/EasyCorp/EasyAdminBundle/issues/1108
                    - property: notices,
                      label: domains.notices,
                      template: '_field_notices.html.twig'
                    - { property: createdAt, label: domains.createdAt }
                    - { property: updatedAt, label: domains.updatedAt }

        DomainsSet:
            label: menu.domainsSets
            class: AppBundle\Entity\DomainsSet
            list:
                title: title.domainsSets
                actions: ['show']
                sort: ['name', 'ASC']
                fields:
                    - { property: name, label: domainsSets.name }
                    - { property: domains, label: domainsSets.domains.nb }
                    - { property: matchingContexts, label: domainsSets.matchingContexts.nb }
            form:
                fields:
                    - { property: name, label: domainsSets.name }
                    - { property: domains, label: domainsSets.domains, type_options: { query_builder: [AppBundle\Controller\AdminController, getDomainNameQueryBuilder] } }
            show:
                max_results: 100
                fields:
                    - { property: id, label: domainsSets.id }
                    - { property: name, label: domainsSets.name }
                    - { property: domains, label: domainsSets.domains }
                    # ugly but https://github.com/EasyCorp/EasyAdminBundle/issues/1108
                    - property: notices,
                      label: domainsSets.notices,
                      template: '_field_notices.html.twig'
                    - { property: createdAt, label: domainsSets.createdAt }
                    - { property: updatedAt, label: domainsSets.updatedAt }


        RestrictedContext:
            class: AppBundle\Entity\RestrictedContext
            label: menu.restrictedContexts
            list:
                title: title.restrictedContexts
                fields:
                    - id
                    - { property: urlRegex, label: restrictedContexts.urlRegex }
            form:
                fields:
                    - { property: urlRegex, label: restrictedContexts.urlRegex }

        User:
            label: menu.users
            class: AppBundle\Entity\User
            list:
                title: title.users
                fields:
                    - { property: username, label: users.username }
                    - { property: email, label: users.email }
                    - { property: enabled, label: users.enabled }
                    - { property: lastLogin, label: users.lastLogin }
                    - { property: roles, label: users.roles }
            edit:
                fields:
                    - { property: username, label: users.username }
                    - { property: email, label: users.email }
                    - { property: enabled, label: users.enabled }
                    - { property: plainPassword, label: users.plainPassword, type: text, type_options: { required: false } }
                    - { property: roles, label: users.roles, type: choice, type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
            new:
                fields:
                    - { property: username, label: users.username }
                    - { property: email, label: users.email }
                    - { property: enabled, label: users.enabled }
                    - { property: plainPassword, label: users.plainPassword, type: text, type_options: { required: true } }
                    - { property: roles, label: users.roles, type: choice, type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
