easy_admin:
    design:
        assets:
            css:
                - 'css/admin.css'
    site_name: 'Le Même En Mieux'
    entities:
        Recommendation:
            class: AppBundle\Entity\Recommendation
            label: 'Recommendation'
            form:
                fields:
                    - title
                    - description
                    - contributor
                    - filters
                    - { property: 'visibility', type: 'choice', type_options: {choices:{'Private': 'private', 'Public': 'public'}} }
                    - { property: 'source', type: 'AppBundle\Form\SourceType' }
                    - { property: 'matchingContexts', type: 'collection', type_options: {entry_type: 'AppBundle\Form\MatchingContextType', allow_add: true, allow_delete: true, by_reference: false} }
                    - { property: 'alternatives', type: 'collection', type_options: {entry_type: 'AppBundle\Form\AlternativeType', allow_add: true, allow_delete: true, by_reference: false} }
        MatchingContext:
            class: AppBundle\Entity\MatchingContext
            disabled_actions: ['new', 'edit']
        Alternative:
            class: AppBundle\Entity\Alternative
            disabled_actions: ['new', 'edit']
        Filter:
            class: AppBundle\Entity\Filter
        User:
            class: AppBundle\Entity\User
            form:
                fields: ['enabled', 'username', 'email', 'roles', 'lastLogin']
        Contributor:
            class: AppBundle\Entity\Contributor
            form:
                fields:
                  - name
                  - organization
                  - { property: 'imageFile', type: 'vich_image' }
