easy_admin:
    site_name: 'DisMoi'
    design:
        form_theme:
            - horizontal
        assets:
            css:
                - 'css/admin.css'
            js:
                - 'js/regex_validator.js'
                - 'js/chartjs/moment.min.js'
                - 'js/chartjs/Chart.js'
                - 'js/custom_graph.js'
                - 'js/short-and-sweet/short-and-sweet.js'
                - 'js/message_validator.js'
                - 'js/filter_table_row.js'
                - 'js/select2.js'
    entities:
        Notice:
            class: AppBundle\Entity\Notice
            label: 'Notices'
            search:
                fields:
                    - matchingContexts.exampleUrl
                    - matchingContexts.domainName
                    - matchingContexts.urlRegex
                    - matchingContexts.excludeUrlRegex
                    - matchingContexts.description
                    - intention
                    - contributor.name
                    - message
                    - note
                    - source.url
                    - expires
            form:
                fields:
                    - { type: 'group', label: Bulle, icon: paper-plane }
                    - { type: 'section', icon: comment, label: Infos à publier }
                    - { property: 'message' }
                    - { property: 'contributor', type_options: { 'query_builder': 'AppBundle\Repository\ContributorRepository::getOrderedList' }}
                    - { property: 'intention', type: 'AppBundle\Form\IntentionType', help: N’apparait pas dans l’extension actuelle }
                    - { property: 'source', type: 'AppBundle\Form\SourceType', label: Source (obsolète), help: Bientôt supprimé }
                    - { type: 'section', icon: lock, label: Gestion }
                    - { property: note, label: Note privée }
                    - { property: 'visibility', type: 'AppBundle\Form\VisibilityType' }
                    - { type: 'group', label: 'Ensembles de pages cibles', icon: 'paper-plane', columns: 6 }
                    - {
                        property: 'matchingContexts',
                        type: 'collection',
                        type_options: {
                            required: true,
                            entry_type: 'AppBundle\Form\MatchingContextType',
                            allow_add: true,
                            allow_delete: true,
                            by_reference: false
                        }
                      }
                    - { type: 'group', label: 'Cycle de vie', icon: 'recycle', columns: 6 }
                    - expires
                    - unpublishedOnExpiration

            list:
                fields:
                    - id
                    - contributor
                    - message
                    - visibility
                    - matchingContexts
                    - { property : 'badgedRatingCount', label: 'Badges', css_class: 'graphable' }
                    - { property : 'displayedRatingCount', label: 'Vues', css_class: 'graphable' }
                    - { property : 'unfoldedRatingCount', label: 'Dépliées', css_class: 'graphable' }
                    - { property : 'clickedRatingCount', label: 'Cliqués', css_class: 'graphable' }
                    - { property : 'likedRatingCount', label: 'Likes', css_class: 'graphable' }
                    - { property : 'dislikedRatingCount', label: 'Dislikes', css_class: 'graphable' }
                    - { property : 'dismissedRatingCount', label: 'Ignorés', css_class: 'graphable' }
                    - expires
                    - created
                    - updated

        ExpiredNotice:
            class: AppBundle\Entity\Notice
            disabled_actions: ['new']
            label: 'Expired Notices'
            search:
                fields:
                    - matchingContexts.urlRegex
                    - matchingContexts.excludeUrlRegex
                    - matchingContexts.description
                    - intention
                    - contributor.name
                    - message
                    - note
                    - source.url
                    - source.label
                    - expires
            list:
                dql_filter: 'entity.expires <= CURRENT_TIMESTAMP()'
                fields:
                    - id
                    - contributor
                    - message
                    - visibility
                    - matchingContexts
                    - { property: 'displayedRatingCount', label: 'Vues', css_class: 'graphable' }
                    - { property : 'unfoldedRatingCount', label: 'Dépliées', css_class: 'graphable' }
                    - { property: 'clickedRatingCount', label: 'Cliqués', css_class: 'graphable' }
                    - { property : 'likedRatingCount', label: 'Likes', css_class: 'graphable' }
                    - { property : 'dislikedRatingCount', label: 'Dislikes', css_class: 'graphable' }
                    - { property: 'dismissedRatingCount', label: 'Ignorés', css_class: 'graphable' }
                    - expires
                    - unpublishedOnExpiration
            form:
                fields:
                    - message
                    - { property: 'contributor', type_options: { 'query_builder': 'AppBundle\Repository\ContributorRepository::getOrderedList' }}
                    - { property: 'intention', type: 'AppBundle\Form\IntentionType' }
                    - note
                    - { property: 'source', type: 'AppBundle\Form\SourceType' }
                    - { property: 'visibility', type: 'AppBundle\Form\VisibilityType' }
                    - { property: 'channels'}
                    - { property: 'matchingContexts', type: 'collection', type_options: {entry_type: 'AppBundle\Form\MatchingContextType', allow_add: true, allow_delete: true, by_reference: false} }
                    - expires
                    - unpublishedOnExpiration

        MatchingContext:
            label: 'Matching Contexts'
            class: AppBundle\Entity\MatchingContext
            disabled_actions: ['new', 'edit']
            list:
                fields:
                    - description
                    - domainNames
                    - domainsSets
                    - notice

        RestrictedContext:
            class: AppBundle\Entity\RestrictedContext
            label: 'Restricted Contexts (global)'
            list:
                fields:
                    - id
                    - { property: urlRegex, label: 'Global Restricted URL Regex' }
            form:
                fields:
                    - { property: urlRegex, label: 'Global Restricted URL Regex' }


        Domain:
            label: 'Domains'
            class: AppBundle\Entity\DomainName
            list:
                actions: ['show']
                fields:
                    - name
                    - { property: 'matchingContexts', label: 'Pages cibles liées' }
                    - { property: 'sets', label: 'Groupes de domaines liés' }
            form:
                fields:
                    - name
                    - { property: 'matchingContexts', label: 'Pages cibles liées' }
                    - { property: 'sets', label: 'Groupes de domaines' }

        Domains_set:
            label: 'Domains Sets'
            class: AppBundle\Entity\DomainsSet
            list:
                actions: ['show']
                fields:
                    - name
                    - { property: 'domains', label: 'Domaines liés' }
                    - { property: 'matchingContexts', label: 'Pages cibles liées' }
            form:
                fields:
                    - name
                    - domains

        User:
            label: "Users"
            class: AppBundle\Entity\User
            list:
                fields:
                - username
                - email
                - enabled
                - lastLogin
                - roles
            edit:
                fields:
                    - username
                    - email
                    - enabled
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
            new:
                fields:
                - username
                - email
                - enabled
                - { property: 'plainPassword', type: 'text', type_options: { required: true } }
                - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }


        Contributor:
            label: "Contributors"
            class: AppBundle\Entity\Contributor
            list:
                sort: ['name', 'ASC']
                fields:
                    - id
                    - name
                    - intro
                    - { property : 'ActiveSubscriptionsCount', label: 'Active Subscribers' }
                    - enabled
            form:
                fields:
                  - name
                  - intro
                  - { property: 'imageFile', type: 'vich_image' }
