app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    schemes: [https]

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    schemes: [https]

api_v1:
    resource: "@AppBundle/Controller/ApiController.php"
    type:     annotation
    prefix:   /api/v1
    schemes: [https]

api_v1_admin:
    resource: "@AppBundle/Controller/AdminApiController.php"
    type:     annotation
    prefix:   /api/v1/admin
    schemes: [https]


easy_admin_bundle:
    resource: "@AppBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin
    schemes: [https]
