app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api_v1:
    resource: "@AppBundle/Controller/ApiController.php"
    type:     annotation
    prefix:   /api/v1

api_v1_admin:
    resource: "@AppBundle/Controller/AdminApiController.php"
    type:     annotation
    prefix:   /api/v1/admin


easy_admin_bundle:
    resource: "@AppBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin
