app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    schemes: [https]

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    schemes: [https]

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: "/resetting"
    schemes: [https]

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: "/profile"
    schemes: [https]

api_v2_admin:
    resource: "@AppBundle/Controller/AdminApiController.php"
    type:     annotation
    prefix:   /api/v2/admin
    schemes: [https]

easy_admin_bundle:
    resource: "@AppBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin
    schemes: [https]

api_v3:
    resource: "@AppBundle/Controller/Api/"
    type:     annotation
    prefix:   /api/v3
    schemes: [https]
